### ISSUE TITLE
Section numbers with trailing zeros

### ISSUE THREAD

**Issue by timtroendle** [tomduck/pandoc-secnos#1]
When a section has a preceding sibling with lower level sections, the section's number is displayed with too many levels and a trailing 0. This may lead to a section numbered `2.0`, although it really should be `2`. 

Here's an almost-minimal example. Source: 

```Markdown
# First Section {#sec:sectionI}

## A subsection

# Second Section {#sec:sectionII}

# Third Section

This is all explained in Sections @sec:sectionI and @sec:sectionII.
```

Result:

```
[...]
This is all explained in Sections 1 and 2.0.
```

Maybe this can be resolved by always removing trailing zeros?

pandoc-secnos: 2.1.1

**Comment by jschlatow** [comment]
This affects html output only.

@timtroendle You may have a look at the commit which I just uploaded. It should solve this issue.

**Comment by timtroendle** [comment]
@ValiValpas Yes, that looks very good. Thanks a lot!

Result using your commit is:

```html
<p>This is all explained in Sections <a href="#sec:sectionI">1</a> and <a href="#sec:sectionII">2</a>.</p>
```

Which is exactly how I'd expect it to be.

**Comment by Dabsen** [comment]
The issue also affected docx output for me, but @ValiValpas' commit seems to fix it in this case as well. Thanks!

**Comment by typeofweb** [comment]
@ValiValpas did you consider creating a PR to this repo?

**Comment by tomduck** [comment]
Thank you all for identifying and resolving this Issue.  I have merged the changes into the `nextrelease` branch.

Cheers,
Tom
